#!/bin/sh -e
#
# Copyright (C) 2014 Linaro Limited
# Author: Peter Maydell <peter.maydell@linaro.org>
# This work is licensed under the terms of the GNU GPL version 2 or later.

# warning: some hard coded paths here

# build-and-test part of a pull request

echo "Doing build and test cycle..."

JFLAG=-j$(nproc)

# test one build from clean, at least:
make --output-sync -C build/alldbg clean
make --output-sync -C build/all $JFLAG
make --output-sync -C build/alldbg $JFLAG
make --output-sync -C build/w32-new $JFLAG
make --output-sync -C build/w64-new $JFLAG
make --output-sync -C build/clang $JFLAG
make --output-sync -C build/all-linux-static $JFLAG
make --output-sync -C build/all check
make --output-sync -C build/alldbg check
make --output-sync -C build/clang check
make --output-sync -C build/all-linux-static check
make --output-sync -C ~/linaro/linux-user-test-0.3/ test
echo "OK DONE x86"
