#!/bin/sh -e

# Copyright (C) 2014 Linaro Limited
# Author: Peter Maydell <peter.maydell@linaro.org>
# This work is licensed under the terms of the GNU GPL version 2 or later.

# Blow away and recreate build directories for merge tree

cd ~/linaro/qemu-for-merges

rm -rf build

do_conf() {
    local buildname="$1"
    shift
    mkdir -p "build/$buildname"
    (cd "build/$buildname" && ../../configure "$@")
}

# do_conf aarch64 '--cross-prefix=aarch64-linux-gnu-' '--target-list=arm-softmmu,aarch64-softmmu'

# do_conf notools '--target-list=arm-softmmu' '--disable-tools' '--cc=ccache gcc'

do_conf all-linux-static '--cc=ccache gcc' '--enable-debug' '--static' '--disable-system'
do_conf all '--cc=ccache gcc'
do_conf alldbg '--cc=ccache gcc' '--enable-debug'
do_conf clang '--cc=clang' '--cxx=clang++' '--enable-gtk' '--extra-cflags=-fsanitize=undefined -Werror'

# -Wno-unused-local-typedefs is working around a problem with the glib version this
# toolchain is using where newer gcc gave a warning about its assert macro. Fixed
# in later glib but I don't care to go through the process of sorting out the libs again.
# TODO could we use --enable-werror rather than -Werror with these compilers ?
do_conf w32-new '--cross-prefix=i686-w64-mingw32-' '--extra-cflags=-I/home/petmay01/linaro/mingw/include -Werror -Wno-unused-local-typedefs' '--extra-ldflags=-L/home/petmay01/linaro/mingw/lib'

# Similar remarks apply here.
do_conf w64-new '--cross-prefix=x86_64-w64-mingw32-' '--extra-cflags=-I/home/petmay01/linaro/mingw64/include -Werror -Wno-unused-local-typedefs' '--extra-ldflags=-L/home/petmay01/linaro/mingw64/lib' '--enable-debug'
